services:
  - type: web
    name: plant-care-ai-assistant
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements-lock.txt
    startCommand: >
      gunicorn "wsgi:app" -w 2 -k gthread --threads 4 -b 0.0.0.0:$PORT
      --max-requests 200 --max-requests-jitter 50 --timeout 120
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: APP_CONFIG
        value: app.config.ProdConfig
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: FLASK_SECRET_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENWEATHER_API_KEY
        sync: false
      - key: RATELIMIT_ENABLED
        value: "true"
      - key: RATELIMIT_DEFAULT
        value: "40 per minute; 2000 per day"
      - key: RATELIMIT_ASK
        value: "8 per minute; 1 per 2 seconds; 200 per day"
      # Optionally add storage if you move off memory:// (recommended in production)
      # - key: RATELIMIT_STORAGE_URI
      #   value: "redis://<host>:6379/0"
